"use client"

import { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { signOut } from "next-auth/react"
import { useTheme } from "next-themes"
import { toast } from "sonner"
import { Download, Plus, RefreshCw, Search, ArrowUpRight, Save, Trash2 } from "lucide-react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { moduleForId, type PlatformModuleId } from "@/lib/platform-modules"
import { operationsRequest, editableModules, csvValue, parseCsv, type OperationsData, type OperationRecord } from "@/lib/operations"
import { FoxWorkspace } from "./fox-workspace"
import { Toaster } from "sonner"

const control="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border/70 bg-card px-4 text-sm font-medium hover:bg-primary/10 focus-visible:outline-2 focus-visible:outline-primary disabled:opacity-50"
const field="min-h-11 w-full rounded-xl border border-border/70 bg-background px-3 py-2 text-base outline-none focus:border-primary sm:text-sm"
const stages=["New lead","New scraped lead","Qualified","Preview generated","Email sent","Opened","Clicked","Replied","Call booked","Proposal sent","Closed won","Closed lost","Fulfillment","Live client","Retainer"]
function value(v:unknown):string {if(v==null||v==="")return "Unknown";return typeof v==="object"?JSON.stringify(v,null,2):String(v)}
function label(s:string){return s.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ")}
function download(name:string,contents:string,type="text/plain") {const u=URL.createObjectURL(new Blob([contents],{type}));const a=document.createElement("a");a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function SourceLink({href,children}:{href:string;children:React.ReactNode}) {
  if(!href.startsWith("/")&&!/^https?:\/\//.test(href))return null
  return href.startsWith("/")?<Link href={href} className={control}>{children}</Link>:<a href={href} target="_blank" rel="noopener noreferrer" className={control}>{children}<ArrowUpRight className="size-4"/></a>
}
function DraftEditor({id,record,onSaved,onClose}:{id:PlatformModuleId;record?:OperationRecord;onSaved:()=>void;onClose:()=>void}) {
  const initial=record?{...record.details,title:record.title,status:record.status}: {title:"",status:id==="leads"?stages[0]:"Draft"}
  const [draft,setDraft]=useState<Record<string,unknown>>(initial)
  const [busy,setBusy]=useState(false)
  const fields=["contacts","companies"].includes(id)?["title","company","email","phone","website","address","owner","nextAction","notes"]:id==="leads"?["title","company","category","address","phone","email","website","mapsUrl","rating","reviewCount","websiteStatus","scoreEvidence","tier","previewUrl","nextAction","lastTouch","notes"]:id==="emailblaster"?["title","subject","body","sequence","suppressions","notes"]:id==="opportunities"?["title","company","value","probability","expectedClose","owner","projectId","nextAction","notes"]:id==="projects"?["title","company","projectId","owner","nextAction","notes"]:["title","projectId","sourceUrl","body","notes"]
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await operationsRequest(id,record?"PATCH":"POST",{...draft,...(record?{id:record.id,updatedAt:record.details.updatedAt}:{})});toast.success("Record saved");onSaved();onClose()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
  return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{record?"Edit":"Add"} {id==="leads"?"agency lead":"record"}</DialogTitle><DialogDescription>Saved to the company workspace with your identity and an audit event. This does not change provider-owned records.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{fields.map(key=><label key={key} className={`space-y-2 text-sm ${["body","notes","sequence","scoreEvidence","suppressions"].includes(key)?"sm:col-span-2":""}`}><span className="capitalize">{key==="title"?"Name":label(key)}</span>{["body","notes","sequence","scoreEvidence","suppressions"].includes(key)?<textarea className={field} rows={4} value={String(draft[key]||"")} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<input className={field} required={key==="title"} type={key==="email"?"email":["website","previewUrl","mapsUrl","sourceUrl"].includes(key)?"url":"text"} value={String(draft[key]??"")} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}</div><label className="block space-y-2 text-sm"><span>Status{ id==="leads"?" (operator-reported)":""}</span>{id==="leads"||id==="emailblaster"?<select className={field} value={String(draft.status)} onChange={e=>setDraft({...draft,status:e.target.value})}>{(id==="leads"?stages:["Draft","Ready for review","Paused"]).map(s=><option key={s}>{s}</option>)}</select>:<input className={field} value={String(draft.status||"")} onChange={e=>setDraft({...draft,status:e.target.value})}/>}</label>{id==="emailblaster"?<p className="text-sm text-amber-300">Saving creates a draft. Delivery is performed through the configured campaign provider after operator review.</p>:null}<div className="sticky bottom-0 flex justify-end gap-3 bg-card py-3"><button type="button" className={control} onClick={onClose}>Cancel</button><button disabled={busy} className={`${control} bg-primary/15 text-primary`}><Save className="size-4"/>{busy?"Saving…":"Save record"}</button></div></form></DialogContent></Dialog>
}
function Preferences(){
  const {theme,setTheme}=useTheme()
  return <section className="space-y-4 rounded-2xl border border-border/60 bg-card/70 p-5">
    <h2 className="text-xl font-bold">Your preferences</h2>
    <p className="text-sm text-muted-foreground">Theme is saved on this browser. Identity and permissions come from ZITADEL.</p>
    <label className="block max-w-sm space-y-2"><span>Theme</span><select className={field} value={theme||"system"} onChange={e=>{setTheme(e.target.value);toast.success("Theme saved")}}><option>system</option><option>dark</option><option>light</option></select></label>
    <div className="flex flex-wrap gap-2"><button className={control} onClick={()=>{setTheme("system");toast.success("Theme reset")}}>Reset theme</button><button className={control} onClick={()=>void signOut({callbackUrl:"/signed-out"})}>Sign out</button></div>
  </section>
}

export function OperationsWorkspace({id,compact=false}:{id:PlatformModuleId;compact?:boolean}) {
  const workspace=moduleForId(id)
  const [data,setData]=useState<OperationsData|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true)
  const [query,setQuery]=useState(""),[status,setStatus]=useState("all"),[source,setSource]=useState("all"),[page,setPage]=useState(0)
  const [selected,setSelected]=useState<OperationRecord|null>(null),[editing,setEditing]=useState<OperationRecord|true|null>(null),[importing,setImporting]=useState(false),[csv,setCsv]=useState(""),[busy,setBusy]=useState(false),[view,setView]=useState("table")
  const refresh=useCallback(async(search="")=>{setLoading(true);setError("");try{setData(await operationsRequest(id,"GET",undefined,search))}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[id])
  useEffect(()=>{void refresh()},[refresh])
  const deferredQuery=useDeferredValue(query)
  const filtered=useMemo(()=>data?.records.filter(r=>(status==="all"||r.status===status)&&(source==="all"||r.source===source)&&`${r.title} ${r.status} ${r.source} ${JSON.stringify(r.details)}`.toLowerCase().includes(deferredQuery.toLowerCase()))||[],[data,status,source,deferredQuery])
  const shown=filtered.slice(page*30,page*30+(compact?8:30))
  async function remove(r:OperationRecord){if(!confirm(`Delete the operator record “${r.title}”? Provider records are unaffected.`))return;try{await operationsRequest(id,"DELETE",{id:r.id,updatedAt:r.details.updatedAt});setSelected(null);toast.success("Record deleted");void refresh()}catch(e){toast.error((e as Error).message)}}
  async function importCsv(){setBusy(true);let count=0;try{const rows=parseCsv(csv);if(rows.length>250)throw new Error("Import up to 250 records at a time.");for(const record of rows){await operationsRequest(id,"POST",{...record,status:record.status||stages[0]});count++}toast.success(`${count} leads imported`);setImporting(false);setCsv("");void refresh()}catch(e){toast.error(`${count} saved. ${(e as Error).message}`);void refresh()}finally{setBusy(false)}}
  return <div className="space-y-5" data-testid="operations-workspace" data-module={id}>
    <Toaster richColors position="bottom-right" />
    {id==="fox"?<FoxWorkspace/>:null}
    {!compact?<header className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs tracking-widest text-primary">{workspace.group}</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight">{workspace.label}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{id==="leads"?"Local businesses, digital infrastructure gaps, personalized offers and fulfillment handoff.":workspace.purpose}</p></div><button className={control} onClick={()=>void refresh(query)} disabled={loading} aria-label="Refresh workspace"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Refresh</button></header>:<div className="flex items-center justify-between"><h2 className="text-xl font-bold">Operating picture</h2><button className={control} onClick={()=>void refresh()} disabled={loading}>Refresh</button></div>}
    {id==="settings"?<Preferences/>:null}
    {error?<div role="alert" className="rounded-xl border border-red-400/30 bg-red-400/5 p-4 text-sm"><p>{error}</p><button className={`${control} mt-3`} onClick={()=>void refresh()}>Retry connection</button></div>:null}
    {loading?<div role="status" className="animate-pulse rounded-xl border border-border p-6 text-sm text-muted-foreground">Reading source records…</div>:null}
    {data?.metrics.length?<section aria-label="Commercial metrics" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map(m=><div key={m.label} className="rounded-xl border border-border/60 bg-card/70 p-5"><p className="text-xs capitalize text-muted-foreground">{label(m.label)}</p><p className="mt-3 font-display text-2xl font-bold tabular-nums">{m.value==null?"Unknown":typeof m.value==="number"&&/value|profit|revenue/i.test(m.label)?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(m.value):String(m.value)}</p></div>)}</section>:null}
    {data?.sources.length?<details aria-label="Source connections" className="rounded-xl border border-border/50 px-3"><summary className="flex min-h-11 cursor-pointer items-center text-xs text-muted-foreground">{data.sources.length} sources · {data.sources.filter(s=>s.status==="CONNECTED").length} connected · Inspect provenance</summary><div className="flex flex-wrap gap-2 pb-3">{data.sources.map((s,i)=><span key={`${s.name}-${i}`} className={`rounded-lg border px-3 py-2 text-xs ${s.status==="CONNECTED"?"border-primary/20 text-primary":"border-amber-400/30 text-amber-300"}`}>{s.name}: {s.status.toLowerCase()}{s.count!==undefined?` · ${s.count} records`:""}</span>)}</div></details>:null}
    {data?.warnings.length?<details className="rounded-xl border border-amber-400/20 p-4 text-sm" open={!compact}><summary className="min-h-11 cursor-pointer text-amber-300">Source limitations and required attention ({data.warnings.length})</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-muted-foreground">{data.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>:null}
    {data?.links.length?<div className="flex flex-wrap gap-2">{data.links.map(l=><SourceLink key={l.href} href={l.href}>{l.label}</SourceLink>)}</div>:null}
    {!compact?<div className="flex flex-wrap gap-3"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2 rounded-xl border border-border/60 bg-card px-3"><Search className="size-4 shrink-0"/><input aria-label="Search records" className="min-w-0 flex-1 bg-transparent py-3 text-base outline-none sm:text-sm" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Search records…"/></label><select aria-label="Filter status" className={`${field} w-[calc(50%-6px)] max-w-full sm:w-auto sm:max-w-60`} value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="all">All statuses</option>{[...new Set(data?.records.map(r=>r.status))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter source" className={`${field} w-[calc(50%-6px)] max-w-full sm:w-auto sm:max-w-60`} value={source} onChange={e=>{setSource(e.target.value);setPage(0)}}><option value="all">All sources</option>{[...new Set(data?.records.map(r=>r.source))].map(s=><option key={s}>{s}</option>)}</select><button className={control} disabled={!data} onClick={()=>{download(`${id}.csv`,["id,title,status,source,details",...filtered.map(r=>[r.id,r.title,r.status,r.source,r.details].map(csvValue).join(","))].join("\r\n"),"text/csv");toast.success("Export downloaded")}}><Download className="size-4"/>Export</button>{editableModules.has(id)&&data?.canWrite?<button className={`${control} text-primary`} onClick={()=>setEditing(true)}><Plus className="size-4"/>{id==="leads"?"Add lead":id==="emailblaster"?"New campaign":"Add record"}</button>:null}{id==="leads"&&data?.canWrite?<button className={control} onClick={()=>setImporting(true)}>Import CSV</button>:null}{["leads","opportunities"].includes(id)?<button className={control} onClick={()=>setView(view==="table"?"pipeline":"table")}>{view==="table"?"Pipeline view":"Table view"}</button>:null}</div>:null}
    <section aria-label="Source records" className="overflow-hidden rounded-2xl border border-border/60 bg-card/70"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/60 p-4"><h2 className="font-display font-bold">{view==="pipeline"?"Pipeline":"Records"}</h2><span className="text-xs text-muted-foreground">{filtered.length} records{data?` · checked ${new Date(data.checkedAt).toLocaleTimeString()}`:""}</span></div>
    {!loading&&!filtered.length?<div className="space-y-3 p-6"><h3 className="font-semibold">{error?"Source records could not be loaded":query||status!=="all"?"No matching records":"No records reported by these sources"}</h3><p className="text-sm text-muted-foreground">{editableModules.has(id)&&data?.canWrite?"Add a company workspace record or import your real data to begin.":"Refresh the sources or use the connected workflow above. No records are assumed to exist."}</p></div>:null}
    {view==="pipeline"?<div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3">{[...new Set(filtered.map(r=>r.status))].map(s=><section key={s} className="rounded-xl bg-background/50 p-3"><h3 className="mb-3 text-sm font-bold">{s} · {filtered.filter(r=>r.status===s).length}</h3>{filtered.filter(r=>r.status===s).map(r=><button key={r.id} onClick={()=>setSelected(r)} className="mb-2 min-h-11 w-full rounded-lg border border-border p-3 text-left text-sm">{r.title}</button>)}</section>)}</div>:<div className="divide-y divide-border/50">{shown.map((r,i)=><button key={`${r.source}-${r.id}-${i}`} onClick={()=>setSelected(r)} className="grid min-h-16 w-full gap-2 px-4 py-4 text-left hover:bg-primary/5 sm:grid-cols-[minmax(0,2fr)_minmax(0,1fr)_minmax(0,1fr)]"><div className="min-w-0"><span className="block break-words text-sm font-semibold">{r.title}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{value(r.details.company_name||r.details.companyName||r.details.subject||r.details.path||r.details.role||r.id)}</span></div><span className="self-center text-xs text-muted-foreground">{r.source}</span><span className="self-center justify-self-start rounded-lg border border-border/60 px-2 py-1 text-xs">{r.status}</span></button>)}</div>}
    {!compact&&filtered.length>30&&view==="table"?<div className="flex items-center justify-between border-t border-border p-3"><button className={control} disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm">Page {page+1} / {Math.ceil(filtered.length/30)}</span><button className={control} disabled={(page+1)*30>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>:null}</section>
    {selected?<Dialog open onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-h-[88dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle className="break-words">{selected.title}</DialogTitle><DialogDescription>{selected.source} · {selected.status}</DialogDescription></DialogHeader><dl className="divide-y divide-border">{Object.entries(selected.details).map(([key,v])=><div key={key} className="py-3"><dt className="mb-1 text-xs capitalize text-muted-foreground">{label(key)}</dt><dd className="whitespace-pre-wrap break-words text-sm [overflow-wrap:anywhere]">{value(v)}</dd></div>)}</dl><div className="flex flex-wrap gap-2">{selected.href?<SourceLink href={selected.href}>Open source workflow</SourceLink>:null}<button className={control} onClick={()=>{download(`${id}-${selected.id.replaceAll("/","_")}.json`,JSON.stringify(selected,null,2),"application/json");toast.success("Record downloaded")}}>Download record</button>{selected.source==="Operator workspace"&&data?.canWrite?<><button className={control} onClick={()=>{setEditing(selected);setSelected(null)}}>Edit</button><button className={`${control} text-red-300`} onClick={()=>void remove(selected)}><Trash2 className="size-4"/>Delete</button></>:null}</div></DialogContent></Dialog>:null}
    {editing?<DraftEditor id={id} record={editing===true?undefined:editing} onSaved={()=>void refresh()} onClose={()=>setEditing(null)}/>:null}
    {importing?<Dialog open onOpenChange={setImporting}><DialogContent><DialogHeader><DialogTitle>Import agency leads</DialogTitle><DialogDescription>CSV columns: title, company, category, phone, email, website, mapsUrl, address, status, nextAction, notes. Up to 250 rows. Imported records are not contacted automatically.</DialogDescription></DialogHeader><input type="file" accept=".csv,text/csv" aria-label="CSV file" className={field} onChange={async e=>{const f=e.target.files?.[0];if(f)setCsv(await f.text())}}/><textarea aria-label="CSV contents" className={field} rows={8} value={csv} onChange={e=>setCsv(e.target.value)}/><button className={control} disabled={busy||!csv} onClick={()=>void importCsv()}>{busy?"Importing…":"Import records"}</button></DialogContent></Dialog>:null}
  </div>
}
