import {test,expect} from '@playwright/test'
import {localAuth} from './local-auth'
test.skip(!process.env.OPERATIONS_AUTH_QA,'Requires the isolated authenticated operations QA server')
test.beforeEach(async({context})=>localAuth(context))

test('agency record persists through reload, edits and deletes in isolated storage',async({page})=>{
  await page.goto('/crm/leads')
  await page.getByRole('button',{name:'Add lead',exact:true}).click()
  await page.getByLabel('Name',{exact:true}).fill('Isolated QA prospect')
  await page.getByLabel('website',{exact:true}).fill('https://example.invalid')
  const saved=page.waitForResponse(r=>r.url().includes('/api/operations/leads')&&r.request().method()==='POST')
  await page.getByRole('button',{name:'Save record',exact:true}).click()
  const savedResponse=await saved
  expect(savedResponse.status(),await savedResponse.text()).toBe(200)
  await expect(page.getByText('Record saved',{exact:true})).toBeVisible()
  await page.reload()
  await page.getByRole('button').filter({hasText:'Isolated QA prospect'}).click()
  await page.getByRole('button',{name:'Edit',exact:true}).click()
  await page.getByLabel('Name',{exact:true}).fill('Updated isolated prospect')
  await page.getByRole('button',{name:'Save record',exact:true}).click()
  await page.getByRole('button').filter({hasText:'Updated isolated prospect'}).click()
  page.once('dialog',d=>d.accept())
  await page.getByRole('button',{name:'Delete',exact:true}).click()
  await expect(page.getByText('Record deleted',{exact:true})).toBeVisible()
  await expect(page.getByText('Updated isolated prospect',{exact:true})).toHaveCount(0)
})

test('mobile catalog detail, filtering and CSV download work',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/bids/catalog')
  await expect(page.getByRole('region',{name:'Source records'}).getByRole('button').first()).toBeVisible()
  await page.getByRole('region',{name:'Source records'}).getByRole('button').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  const downloaded=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export',exact:true}).click()
  expect((await downloaded).suggestedFilename()).toBe('catalog.csv')
  await page.getByRole('textbox',{name:'Search records'}).fill('no-such-sku-for-isolated-test')
  await expect(page.getByText('No matching records',{exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'/tmp/vulpine-operations-catalog-mobile.png'})
})

test('session contains no provider tokens; unauthenticated and insufficient-role requests fail closed',async({context,page})=>{
  const session=await(await context.request.get('/api/auth/session')).json()
  expect(session.user.id).toBe('isolated-qa-user')
  expect(JSON.stringify(session)).not.toMatch(/access_token|refresh_token|id_token|client_secret/)
  expect((await context.request.post('/api/operations/leads',{headers:{origin:'https://untrusted.invalid'},data:{title:'must not save'}})).status()).toBe(403)
  await page.goto('/settings')
  await page.getByRole('button',{name:'Sign out',exact:true}).click()
  await expect(page).toHaveURL(/\/signed-out$/)
  expect((await context.request.get('/api/operations/projects')).status()).toBe(401)
  await localAuth(context,['estimator'])
  expect((await context.request.get('/api/operations/providers')).status()).toBe(403)
  await context.clearCookies()
  expect((await context.request.get('/api/operations/projects')).status()).toBe(401)
  await page.goto('/crm/leads')
  await expect(page).toHaveURL(/\/api\/auth\/signin/)
})

test('source failure is actionable and never displays invented records',async({page})=>{
  await page.route('**/api/operations/leads',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Source unavailable for isolated test'})}))
  await page.goto('/crm/leads')
  await expect(page.getByTestId('operations-workspace').getByRole('alert')).toContainText('Source unavailable for isolated test')
  await expect(page.getByRole('button',{name:'Retry connection'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Add lead',exact:true})).toHaveCount(0)
})
